# Generated by Django 3.2.15 on 2022-10-10 00:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'discussion',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('difficulty', models.IntegerField(default=0)),
                ('details', models.TextField()),
                ('fun_name', models.CharField(max_length=255)),
                ('code', models.TextField()),
                ('qoutput', models.CharField(max_length=255)),
                ('hint', models.TextField()),
                ('nanswer', models.IntegerField(default=0)),
                ('ncorrect', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.category')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('sex', models.IntegerField(default=0)),
                ('user_image', models.ImageField(default='None', upload_to='static/media/head_img', verbose_name='user_image')),
                ('email', models.CharField(max_length=100)),
                ('qpass', models.IntegerField(default=0)),
                ('qtry', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='User_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pss', models.IntegerField(default=9)),
                ('subcode', models.TextField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.users')),
            ],
            options={
                'db_table': 'user_question',
            },
        ),
        migrations.CreateModel(
            name='User_Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('discussion_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.discussion')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.users')),
            ],
            options={
                'db_table': 'user_discussion',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.users'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.users'),
        ),
    ]
