# Generated by Django 3.2.15 on 2022-10-10 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_discussion',
            old_name='discussion_id',
            new_name='discussion',
        ),
        migrations.RenameField(
            model_name='user_discussion',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_question',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='user_question',
            old_name='user_id',
            new_name='user',
        ),
    ]
